import type { ProjectAnalysisManifest } from "./types.js";

const pluginKey = (name: string, vendor?: string, format?: string) =>
  `${vendor ?? ""}|${name}|${format ?? ""}`;

export const formatPluginChecklistMarkdown = (analysis: ProjectAnalysisManifest): string => {
  const lines: string[] = [
    `# Plugin checklist — ${analysis.projectName}`,
    "",
    `- **DAW:** ${analysis.daw === "ableton" ? "Ableton Live" : "FL Studio"}`,
    `- **Source:** ${analysis.sourceFile.name}`,
    analysis.tempo ? `- **Tempo:** ${analysis.tempo} BPM` : null,
    "",
    "## Plugins",
    ""
  ].filter((line): line is string => line !== null);

  if (!analysis.pluginsSummary.length) {
    lines.push("_No plugins detected._", "");
  } else {
    for (const plugin of analysis.pluginsSummary) {
      const vendor = plugin.vendor ? ` (${plugin.vendor})` : "";
      const tracks =
        plugin.usedOnTracks.length > 0 ? ` — tracks: ${plugin.usedOnTracks.join(", ")}` : "";
      lines.push(`- [ ] **${plugin.name}**${vendor} · \`${plugin.format}\`${tracks}`);
    }
    lines.push("");
  }

  if (analysis.warnings.length) {
    lines.push("## Warnings", "");
    for (const warning of analysis.warnings) {
      lines.push(`- \`${warning.code}\`: ${warning.message}`);
    }
    lines.push("");
  }

  lines.push("---", "_Generated by Meshroom_");
  return lines.join("\n");
};

export const formatPluginChecklistPlain = (analysis: ProjectAnalysisManifest): string => {
  const header = `Plugin checklist — ${analysis.projectName} (${analysis.daw})`;
  const plugins = analysis.pluginsSummary.map((plugin) => {
    const vendor = plugin.vendor ? ` (${plugin.vendor})` : "";
    return `[ ] ${plugin.name}${vendor} [${plugin.format}]`;
  });
  return [header, "", ...plugins].join("\n");
};

export const uniquePluginCount = (analysis: ProjectAnalysisManifest) => {
  const seen = new Set<string>();
  for (const plugin of analysis.pluginsSummary) {
    seen.add(pluginKey(plugin.name, plugin.vendor, plugin.format));
  }
  return seen.size;
};
