import type { ProjectAnalysisManifest } from "./dawTypes";

export const formatPluginChecklistMarkdown = (analysis: ProjectAnalysisManifest): string => {
  const lines: string[] = [
    `# Plugin checklist — ${analysis.projectName}`,
    "",
    `- **DAW:** ${analysis.daw === "ableton" ? "Ableton Live" : "FL Studio"}`,
    `- **Source:** ${analysis.sourceFile.name}`,
    analysis.tempo ? `- **Tempo:** ${analysis.tempo} BPM` : null,
    "",
    "## Plugins",
    ""
  ].filter((line): line is string => line !== null);

  if (!analysis.pluginsSummary.length) {
    lines.push("_No plugins detected._", "");
  } else {
    for (const plugin of analysis.pluginsSummary) {
      const vendor = plugin.vendor ? ` (${plugin.vendor})` : "";
      const tracks =
        plugin.usedOnTracks.length > 0 ? ` — tracks: ${plugin.usedOnTracks.join(", ")}` : "";
      lines.push(`- [ ] **${plugin.name}**${vendor} · \`${plugin.format}\`${tracks}`);
    }
    lines.push("");
  }

  if (analysis.warnings.length) {
    lines.push("## Warnings", "");
    for (const warning of analysis.warnings) {
      lines.push(`- \`${warning.code}\`: ${warning.message}`);
    }
    lines.push("");
  }

  lines.push("---", "_Generated by Meshroom_");
  return lines.join("\n");
};

export const formatOpenInDawHints = (analysis: ProjectAnalysisManifest) => {
  const dawLabel = analysis.daw === "ableton" ? "Ableton Live" : "FL Studio";
  const steps =
    analysis.daw === "ableton"
      ? [
          `Download **${analysis.sourceFile.name}** from Meshroom.`,
          "In Ableton Live: **File → Open Live Set…** and select the downloaded `.als` file.",
          "If samples are missing, use **Collect All and Save** or relink from the warnings list."
        ]
      : [
          `Download **${analysis.sourceFile.name}** from Meshroom.`,
          "In FL Studio: **File → Open** and select the downloaded `.flp` file.",
          "Relink missing samples via the Browser or warning paths below."
        ];

  const sampleWarnings = analysis.warnings.filter(
    (warning) =>
      warning.code === "MISSING_SAMPLE_PATH" ||
      warning.message.toLowerCase().includes("sample")
  );

  return { dawLabel, steps, sampleWarnings };
};
